-- List all students who are not in the fifth year
SELECT ID_STUDENT, FIRST_NAME || ' ' || LAST_NAME AS "Student", YEAR AS "Year"
FROM STUDENTS
WHERE YEAR < 5
ORDER BY LAST_NAME;


-- Display information about courses and professors
SELECT COURSES.COURSE_NAME AS "Course", COURSES.CODE AS "Code", COURSES.REQUIRED_OPTIONAL AS "Required/Optional", 
       PROFESSORS.TITLE || ' ' || PROFESSORS.FIRST_NAME || ' ' || PROFESSORS.LAST_NAME AS "Professor", 
       COURSES.ECTS AS "ECTS Credits", COURSES.YEAR AS "Year"
FROM COURSES LEFT JOIN PROFESSORS ON COURSES.ID_PROFESSOR = PROFESSORS.ID_PROFESSOR
ORDER BY COURSES.COURSE_NAME;


-- List all professors who are not from the Informatics department
SELECT PROFESSORS.TITLE || ' ' || PROFESSORS.FIRST_NAME || ' ' || PROFESSORS.LAST_NAME AS "Professor", 
       DEPARTMENTS.DEPARTMENT_NAME AS "Department"
FROM DEPARTMENTS INNER JOIN PROFESSORS ON DEPARTMENTS.ID_DEPARTMENT = PROFESSORS.ID_DEPARTMENT
WHERE DEPARTMENTS.DEPARTMENT_NAME NOT LIKE 'Informatics'
ORDER BY DEPARTMENTS.DEPARTMENT_NAME;


-- List all courses scheduled for 1st February 2017
SELECT COURSES.COURSE_NAME AS "Course", EXAM_SESSIONS.SESSION_DATE AS "Exam Date", 
       EXAM_SESSIONS.SESSION_TIME AS "Exam Time", EXAM_SESSIONS.SESSION_ROOM AS "Room"
FROM COURSES LEFT JOIN EXAM_SESSIONS ON COURSES.ID_COURSE = EXAM_SESSIONS.ID_COURSE
WHERE EXAM_SESSIONS.SESSION_DATE = '2017-02-01'
ORDER BY COURSES.COURSE_NAME;


-- List all students who have registered for an exam session
SELECT STUDENTS.ID_STUDENT, STUDENTS.FIRST_NAME || ' ' || STUDENTS.LAST_NAME AS "Student", 
       COURSES.COURSE_NAME AS "Course", REGISTRATIONS.ATTEMPT AS "Attempt", 
       EXAM_SESSIONS.SESSION_DATE AS "Exam Date", EXAM_SESSIONS.SESSION_TIME AS "Exam Time", 
       EXAM_SESSIONS.SESSION_ROOM AS "Room"
FROM ((STUDENTS LEFT JOIN REGISTRATIONS ON STUDENTS.ID_STUDENT = REGISTRATIONS.ID_STUDENT) 
       LEFT JOIN EXAM_SESSIONS ON REGISTRATIONS.ID_EXAM_SESSION = EXAM_SESSIONS.ID_SESSION) 
       LEFT JOIN COURSES ON REGISTRATIONS.ID_COURSE = COURSES.ID_COURSE
WHERE COURSES.COURSE_NAME IS NOT NULL
ORDER BY STUDENTS.LAST_NAME;


-- List all exam sessions for the course "Data Management"
SELECT COURSES.COURSE_NAME AS "Course", EXAM_SESSIONS.SESSION_DATE AS "Exam Date", 
       EXAM_SESSIONS.SESSION_TIME AS "Exam Time", EXAM_SESSIONS.SESSION_ROOM AS "Room"
FROM COURSES LEFT JOIN EXAM_SESSIONS ON COURSES.ID_COURSE = EXAM_SESSIONS.ID_COURSE
WHERE COURSES.COURSE_NAME = 'Data Management'
ORDER BY COURSES.COURSE_NAME;

